version: '3'

services:
  db:
    image: mongo
    container_name: chat-db
    ports:
      - '27017:27017'
    user: $UID
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=chat
      - DB_USERNAME=admin
      - DB_PASSWORD=secret
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./data:/data/db

  cache:
    image: redis:alpine
    container_name: chat-cache
    ports:
      - '6379:6379'
    command: ['--requirepass "secret"']
